-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.triviagame_category DROP CONSTRAINT IF EXISTS "fk_Category_Episode";

ALTER TABLE IF EXISTS public.triviagame_customgame DROP CONSTRAINT IF EXISTS "fk_CustomGame_User";

ALTER TABLE IF EXISTS public.triviagame_customgame_has_category DROP CONSTRAINT IF EXISTS "fk_CustomGame_has_Category_CustomGame";

ALTER TABLE IF EXISTS public.triviagame_customgame_has_category DROP CONSTRAINT IF EXISTS "fk_CustomGame_has_Category_Category";

ALTER TABLE IF EXISTS public.triviagame_question DROP CONSTRAINT IF EXISTS "fk_Question_Category";



DROP TABLE IF EXISTS public.triviagame_category;

CREATE TABLE IF NOT EXISTS public.triviagame_category
(
    idcategory integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    round smallint NOT NULL,
    episode_idepisode integer NOT NULL,
    CONSTRAINT "Category_pkey" PRIMARY KEY (idcategory)
);

DROP TABLE IF EXISTS public.triviagame_customgame;

CREATE TABLE IF NOT EXISTS public.triviagame_customgame
(
    idcustomgame integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_iduser character varying(512) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (idcustomgame)
);

DROP TABLE IF EXISTS public.triviagame_customgame_has_category;

CREATE TABLE IF NOT EXISTS public.triviagame_customgame_has_category
(
    customgame_idcustomgame integer NOT NULL,
    category_idcategory integer NOT NULL,
    PRIMARY KEY (customgame_idcustomgame, category_idcategory)
);

DROP TABLE IF EXISTS public.triviagame_episode;

CREATE TABLE IF NOT EXISTS public.triviagame_episode
(
    idepisode integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    air_date date NOT NULL,
    season_number integer NOT NULL,
    episode_number smallint NOT NULL,
    CONSTRAINT "Episode_pkey" PRIMARY KEY (idepisode),
    CONSTRAINT "Episode_air_date_key" UNIQUE (air_date)
);

DROP TABLE IF EXISTS public.triviagame_question;

CREATE TABLE IF NOT EXISTS public.triviagame_question
(
    idquestion integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    clue_value smallint NOT NULL,
    comment text COLLATE pg_catalog."default",
    question text COLLATE pg_catalog."default" NOT NULL,
    answer text COLLATE pg_catalog."default" NOT NULL,
    category_idcategory integer NOT NULL,
    CONSTRAINT "Question_pkey" PRIMARY KEY (idquestion)
);

DROP TABLE IF EXISTS public.triviagame_user;

CREATE TABLE IF NOT EXISTS public.triviagame_user
(
    iduser character varying(512) NOT NULL,
    PRIMARY KEY (iduser)
);

ALTER TABLE IF EXISTS public.triviagame_category
    ADD CONSTRAINT "fk_Category_Episode" FOREIGN KEY (episode_idepisode)
    REFERENCES public.triviagame_episode (idepisode) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.triviagame_customgame
    ADD CONSTRAINT "fk_CustomGame_User" FOREIGN KEY (user_iduser)
    REFERENCES public.triviagame_user (iduser) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.triviagame_customgame_has_category
    ADD CONSTRAINT "fk_CustomGame_has_Category_CustomGame" FOREIGN KEY (customgame_idcustomgame)
    REFERENCES public.triviagame_customgame (idcustomgame) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.triviagame_customgame_has_category
    ADD CONSTRAINT "fk_CustomGame_has_Category_Category" FOREIGN KEY (category_idcategory)
    REFERENCES public.triviagame_category (idcategory) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.triviagame_question
    ADD CONSTRAINT "fk_Question_Category" FOREIGN KEY (category_idcategory)
    REFERENCES public.triviagame_category (idcategory) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;
